repository:
  name: probot-test
  description: my testing repo for probotapplications. Keep it clean
  homepage: https://github.com/apps/settings
  topics: probot-app, github-app, test
  has_wiki: false
