repository:
  name: probot-test
  description: my testing repo for probot applications. Keep it clean, okay? testing 1234567
  homepage: https://github.com/vidu171/settings
  topics: probot-app, github-app, test
  has_wiki: false
labels:
  - name: test
    color: CC0000
    description: 'Test description'
  - name: feature
    color: 336699
  