repository:
  name: TEst Playgroung
  description: Sandbox repo for probot applications. Keep it clean. Or Maybe not. Waba lubba dub dub 1234567
  homepage: https://github.com/vidu171/settings
  topics: Sandbox, waba-luba-dub-dub, test
  has_wiki: false
labels:
  - name: test
    color: CC0000
    description: 'Test description'
  - name: feature
    color: 336699
  
