repository:
  name: probot-test
  description: my testing repo for probot applications. Keep it clean
  homepage: https://github.com/vidu171/settings
  topics: probot-app, github-app, test
  has_wiki: false
